version: '3'
services:
  mysql:
    image: "docker.io/mysql:8.0.27"
    container_name: mysql-container
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: 'test'
      MYSQL_PASS: '123456'
      MYSQL_DATABASE: 'demo'